export const ERROR_CODES = {
  MISSING_REQUIRED_PARAMETER: 'MISSING_REQUIRED_PARAMETER',
  CAMPAIGN_NOT_FOUND: 'CAMPAIGN_NOT_FOUND',
  DOMAIN_NOT_FOUND: 'DOMAIN_NOT_FOUND',
  LANGUAGE_NOT_FOUND: 'LANGUAGE_NOT_FOUND',
  INVALID_JOB_GROUP: 'INVALID_JOB_GROUP',
  HQ_DOMAIN_NOT_FOUND: 'HQ_DOMAIN_NOT_FOUND',
  HQ_QUESTIONS_NOT_REGISTERED: 'HQ_QUESTIONS_NOT_REGISTERED',
  HQ_QUESTION_NOT_FOUND: 'HQ_QUESTION_NOT_FOUND',
  FILE_NAME_MISMATCH: 'FILE_NAME_MISMATCH',
  NO_FILE_RECEIVED: 'NO_FILE_RECEIVED',
  BADGE_IMAGE_NOT_FOUND: 'BADGE_IMAGE_NOT_FOUND',
  INVALID_FILE_NAME: 'INVALID_FILE_NAME',
  NO_DATA_FOUND: 'NO_DATA_FOUND',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
