import { Job } from "@/types/pages/register/types";

export const defaultLanguageCode = "en-US";
export const sumtotalUserOthersJobId = "7";
export const sumtotalUserOthersJobCode = "fsm";
export const defaultLanguages = [
  { code: "ar-AE", name: "Arabic (United Arab Emirates)" },
  { code: "az", name: "Azerbajiani" },
  { code: "bg", name: "Bulgarian" },
  { code: "bn", name: "Bengali(Bangladesh)" },
  { code: "bs", name: "Bosnian" },
  { code: "cs", name: "Czech" },
  { code: "da", name: "Danish" },
  { code: "de-DE", name: "(deprecated) German(Germany)" },
  { code: "el", name: "Greek" },
  { code: "en-GB", name: "English(UnitedKingdom)" },
  { code: "en-US", name: "(deprecated) English(UnitedStates)" },
  { code: "es-LTN", name: "(deprecated) Spanish(LTN)" },
  { code: "es-ES", name: "(deprecated) Spanish(Spain)" },
  { code: "et", name: "Estonian(Estonia)" },
  { code: "fi", name: "Finnish" },
  { code: "fr-CA", name: "French(Canada)" },
  { code: "fr-FR", name: "(deprecated) French(France)" },
  { code: "he", name: "Hebrew" },
  { code: "hr-HR", name: "(deprecated) Croatian(Croatia)" },
  { code: "hu", name: "Hungarian" },
  { code: "id", name: "Indonesian" },
  { code: "it-IT", name: "(deprecated) Italian(Italy)" },
  { code: "ja", name: "Japanese" },
  { code: "ka", name: "Georgian" },
  { code: "km", name: "Khmer(Cambodia)" },
  { code: "lo", name: "Lao(LaoP.D.R.)" },
  { code: "lt", name: "Lithuanian(Lithuania)" },
  { code: "mk", name: "Macedonian" },
  { code: "my", name: "Burmese(Myanmar)" },
  { code: "nb", name: "Norwegian(Bokmal)" },
  { code: "pl", name: "Polish" },
  { code: "pt-BR", name: "Portuguese(Brazil)" },
  { code: "pt-PT", name: "(deprecated) Portuguese(Portugal)" },
  { code: "ro", name: "Romanian" },
  { code: "ru", name: "Russian" },
  { code: "sk-SK", name: "(deprecated) Slovakian(Slovakia)" },
  { code: "sl", name: "Slovenian" },
  { code: "sq", name: "Albanian" },
  { code: "sr-Cyrl", name: "(deprecated) Serbian(Cyrillic)" },
  { code: "sv", name: "Swedish(Sweden)" },
  { code: "th", name: "Thai" },
  { code: "tr", name: "Turkish" },
  { code: "uz", name: "Uzbek(Cyrillic)" },
  { code: "vi", name: "Vietnamese" },
  { code: "zh-CN", name: "Chinese(Simplified)" },
  { code: "zh-TW", name: "Chinese(Traditional)" },
  { code: "zh-HK", name: "Chinese(Traditional)" },
  { code: "lv", name: "Latvian(Latvia)" },
  { code: "ko", name: "Korean" },
  { code: "en-US-my", name: "(deprecated) Language for Malaysia" },
  { code: "en-US-au", name: "(deprecated) Language for Australia" },
  { code: "fr-FR-cm", name: "(deprecated) Language for Cameroon" },
  { code: "fr-FR-ci", name: "(deprecated) Language for Ivory Coast" },
  { code: "fr-FR-dz", name: "(deprecated) Language for Algeria" },
  { code: "es-LTN-co", name: "(deprecated) Language for Colombia" },
  { code: "fr-FR-fr", name: "(deprecated) Language for France" },
  { code: "es-LTN-mx", name: "(deprecated) Language for Mexico" },
  { code: "fr-FR-ma", name: "(deprecated) Language for Morocco" },
  { code: "es-LTN-pr", name: "(deprecated) Language for Peru" },
  { code: "fr-FR-sn", name: "(deprecated) Language for Senegal" },
  { code: "fr-FR-ch", name: "(deprecated) Language for Switzerland" },
  { code: "fr-FR-TN", name: "(deprecated) Language for Tunisia" },
  { code: "uk", name: "Ukraine" },
  { code: "ar-TN", name: "Tunisia, Arabic" },
  { code: "ar", name: "Arabic" },
  { code: "de", name: "German" },
  { code: "en", name: "English(USA)" },
  { code: "es", name: "Spanish(Spain)" },
  { code: "es-419", name: "Spanish(LTN)" },
  { code: "fr", name: "French(France)" },
  { code: "hr", name: "Croatian" },
  { code: "it", name: "Italian" },
  { code: "ky", name: "Kyrgyz" },
  { code: "pt", name: "Portuguese(Portugal)" },
  { code: "sk", name: "Slovak" },
  { code: "sr", name: "Serbian" },
  { code: "tg", name: "Tajiki" },
];

export const defaultLanguagesByRegion = {
  EUROPE: [
    "sq",
    "bs",
    "hr-HR",
    "mk",
    "sr-Cyrl",
    "sl",
    "de-DE",
    "fr-FR",
    "it-IT",
    "en-US",
    "et",
    "lv",
    "lt",
    "cs",
    "sk-SK",
    "el",
    "hu",
    "es-ES",
    "pt-PT",
    "sv",
    "fi",
    "nb",
    "da",
    "pl",
    "bg",
    "ro",
  ],
  CIS: ["ru", "uz", "az", "ka"],
  China: ["zh-TW", "zh-HK"],
  SEAO: ["vi", "en-US", "id", "th", "km", "lo", "my"],
  SEUC: ["uk"],
  SWA: ["bn", "en-US"],
  MENA: ["ar-AE", "he", "en-US", "fr-FR", "tr"],
  LATAM: ["pt-BR", "en-US", "es-LTN"],
  AFRICA: ["en-US", "fr-FR"],
  Japan: ["ja"],
};

export const arabicDomains = ["NAT_2818", "NAT_37602", "NAT_2275", "NAT_2400", "NAT_2368"];

export const arabicCountries = ["Egypt", "Israel", "Palestine", "Jordan", "Iraq"];

export const myanmarDomainCode = "NAT_2368";

export const defaultJobs: Job[] = [
  { name: "FSM", group: "fsm", value: "8", id: "8" },
  { name: "FF", group: "ff", value: "9", id: "9" },
  { name: "FSM(SES)", group: "fsm", value: "10", id: "8", storeId: "4" },
  { name: "FF(SES)", group: "ff", value: "11", id: "9", storeId: "4" },
];
