export const defaultLanguageCode = "en-US";
export const sumtotalUserOthersJobId = "7";
export const defaultLanguages = [
  { code: "ar-AE", name: "Language for AR AE" },
  { code: "az", name: "Language for AZ" },
  { code: "bg", name: "Language for BG" },
  { code: "bn", name: "Language for BN" },
  { code: "bs", name: "Language for BS" },
  { code: "cs", name: "Language for CS" },
  { code: "da", name: "Language for DA" },
  { code: "de-DE", name: "Language for DE DE" },
  { code: "el", name: "Language for EL" },
  { code: "en-GB", name: "Language for EN GB" },
  { code: "en-US", name: "Language for EN US" },
  { code: "es-LTN", name: "Language for ES 419" },
  { code: "es-ES", name: "Language for ES ES" },
  { code: "et", name: "Language for ET" },
  { code: "fi", name: "Language for FI" },
  { code: "fr-CA", name: "Language for FR CA" },
  { code: "fr-FR", name: "Language for FR FR" },
  { code: "he", name: "Language for HE" },
  { code: "hr-HR", name: "Language for HR HR" },
  { code: "hu", name: "Language for HU" },
  { code: "id", name: "Language for ID" },
  { code: "it-IT", name: "Language for IT IT" },
  { code: "ja", name: "Language for JA" },
  { code: "ka", name: "Language for KA" },
  { code: "km", name: "Language for KM" },
  { code: "lo", name: "Language for LO" },
  { code: "lt", name: "Language for LT" },
  { code: "mk", name: "Language for MK" },
  { code: "my", name: "Language for MY" },
  { code: "nb", name: "Language for NB" },
  { code: "pl", name: "Language for PL" },
  { code: "pt-BR", name: "Language for PT BR" },
  { code: "pt-PT", name: "Language for PT PT" },
  { code: "ro", name: "Language for RO" },
  { code: "ru", name: "Language for RU" },
  { code: "sk-SK", name: "Language for SK SK" },
  { code: "sl", name: "Language for SL" },
  { code: "sq", name: "Language for SQ" },
  { code: "sr-Cyrl", name: "Language for SR CYRL" },
  { code: "sv", name: "Language for SV" },
  { code: "th", name: "Language for TH" },
  { code: "tr", name: "Language for TR" },
  { code: "uz", name: "Language for UZ" },
  { code: "vi", name: "Language for VI" },
  { code: "zh-HK", name: "Language for ZH HK" },
  { code: "zh-TW", name: "Language for ZH TW" },
  { code: "lv", name: "Language for lv" },
  { code: "uk", name: "Language for uk" },
];
export const defualtLanguagesByRegion = {
  EUROPE: [
    "sq",
    "bs",
    "hr-HR",
    "mk",
    "sr-Cyrl",
    "sl",
    "de-DE",
    "fr-FR",
    "it-IT",
    "en-US",
    "et",
    "lv",
    "lt",
    "cs",
    "sk-SK",
    "el",
    "hu",
    "es-ES",
    "pt-PT",
    "sv",
    "fi",
    "nb",
    "da",
    "pl",
    "bg",
    "ro",
  ],
  CIS: ["ru", "uz", "az", "ka"],
  China: ["zh-TW", "zh-HK"],
  SEAO: ["vi", "en-US", "id", "th", "km", "lo", "my"],
  SEUC: ["uk"],
  SWA: ["bn", "en-US"],
  MENA: ["ar-AE", "he", "en-US", "fr-FR", "tr"],
  LATAM: ["pt-BR", "en-US", "es-LTN"],
  AFRICA: ["en-US", "fr-FR"],
  Japan: ["ja"],
};
