import {
  filterResultsByLatestDate,
  OrganizationResult,
  PersonOrganization,
} from "./sumtotal";

describe("filterResultsByLatestDate", () => {
  it("should filter out duplicate integer1 values and keep the latest by joiningDate", () => {
    const personOrganization: PersonOrganization[] = [
      {
        organizationId: 506631,
        isPrimary: false,
        joiningDate: "2024-11-11T15:00:00Z",
        code: "OrgCode-1981",
        deleted: 0,
        mainOrganization: false,
      },
      {
        organizationId: 751755,
        isPrimary: true,
        joiningDate: "2024-11-29T08:11:42.283Z",
        code: "HQ_test_SES store",
        deleted: 0,
        mainOrganization: false,
      },
      {
        organizationId: 751796,
        isPrimary: false,
        joiningDate: "2024-12-20T06:10:56.06Z",
        code: "HQ_api test store",
        deleted: 0,
        mainOrganization: false,
      },
    ];

    const results: OrganizationResult[] = [
      {
        pagination: { offset: 1, limit: 10, total: 1 },
        data: [
          {
            organizationId: 751796,
            orgDomainInd: false,
            hierarchyId: 0,
            contactUserId: 0,
            name: "HQ_api test store",
            orgTypeCode: null,
            personCount: 0,
            code: "HQ_api test store",
            contactEmail: null,
            parentOrganizationName: "HQ_api test channel",
            childOrgsCount: 0,
            pageNum: 0,
            orgPlaceHolder: false,
            depth: 0,
            optionalInfo: {
              integer1: 5,
              text1: "",
              text2: null,
              text3: null,
              text4: null,
              text5: null,
              text6: null,
              text7: null,
              text8: null,
              text9: null,
              text10: null,
              text11: null,
              text12: null,
              text13: null,
              text14: null,
              text15: null,
              date1: null,
              date2: null,
              integer2: null,
              float1: null,
              float2: null,
              decimal1: null,
              decimal2: null,
              ind1: null,
              ind2: null,
              money1: null,
              money2: null,
              memo1: null,
              memo2: null,
              currencyId: null,
            },
            hierarchyName: "Samsung",
            orgContactInfo: null,
          },
        ],
      },
      {
        pagination: { offset: 1, limit: 10, total: 1 },
        data: [
          {
            organizationId: 751755,
            orgDomainInd: false,
            hierarchyId: 0,
            contactUserId: 0,
            name: "HQ_test_SES store",
            orgTypeCode: null,
            personCount: 0,
            code: "HQ_test_SES store",
            contactEmail: null,
            parentOrganizationName: "HQ Channel",
            childOrgsCount: 0,
            pageNum: 0,
            orgPlaceHolder: false,
            depth: 0,
            optionalInfo: {
              integer1: 5,
              text1: "",
              text2: null,
              text3: null,
              text4: null,
              text5: null,
              text6: null,
              text7: null,
              text8: null,
              text9: null,
              text10: null,
              text11: null,
              text12: null,
              text13: null,
              text14: null,
              text15: null,
              date1: null,
              date2: null,
              integer2: null,
              float1: null,
              float2: null,
              decimal1: null,
              decimal2: null,
              ind1: null,
              ind2: null,
              money1: null,
              money2: null,
              memo1: null,
              memo2: null,
              currencyId: null,
            },
            hierarchyName: "Samsung",
            orgContactInfo: null,
          },
        ],
      },
      {
        pagination: { offset: 1, limit: 10, total: 1 },
        data: [
          {
            organizationId: 506631,
            orgDomainInd: false,
            hierarchyId: 0,
            contactUserId: 0,
            name: "HQ_Job_Group",
            orgTypeCode: null,
            personCount: 0,
            code: "OrgCode-1981",
            contactEmail: null,
            parentOrganizationName: "HQ Retail Group",
            childOrgsCount: 0,
            pageNum: 0,
            orgPlaceHolder: false,
            depth: 0,
            optionalInfo: {
              integer1: 7,
              text1: "",
              text2: null,
              text3: null,
              text4: null,
              text5: null,
              text6: null,
              text7: null,
              text8: null,
              text9: null,
              text10: null,
              text11: null,
              text12: null,
              text13: null,
              text14: null,
              text15: null,
              date1: null,
              date2: null,
              integer2: null,
              float1: null,
              float2: null,
              decimal1: null,
              decimal2: null,
              ind1: null,
              ind2: null,
              money1: null,
              money2: null,
              memo1: null,
              memo2: null,
              currencyId: null,
            },
            hierarchyName: "Samsung",
            orgContactInfo: null,
          },
        ],
      },
    ];

    const expectedOutput = [
      {
        organizationId: 751796,
        orgDomainInd: false,
        hierarchyId: 0,
        contactUserId: 0,
        name: "HQ_api test store",
        orgTypeCode: null,
        personCount: 0,
        code: "HQ_api test store",
        contactEmail: null,
        parentOrganizationName: "HQ_api test channel",
        childOrgsCount: 0,
        pageNum: 0,
        orgPlaceHolder: false,
        depth: 0,
        optionalInfo: {
          integer1: 5,
          text1: "",
        },
        hierarchyName: "Samsung",
        orgContactInfo: null,
      },
      {
        organizationId: 506631,
        orgDomainInd: false,
        hierarchyId: 0,
        contactUserId: 0,
        name: "HQ_Job_Group",
        orgTypeCode: null,
        personCount: 0,
        code: "OrgCode-1981",
        contactEmail: null,
        parentOrganizationName: "HQ Retail Group",
        childOrgsCount: 0,
        pageNum: 0,
        orgPlaceHolder: false,
        depth: 0,
        optionalInfo: {
          integer1: 7,
          text1: "",
        },
        hierarchyName: "Samsung",
        orgContactInfo: null,
      },
    ];
    const expectedIds = [751796, 506631]; // Expected organization IDs

    const result = filterResultsByLatestDate(results, personOrganization);

    // Extract remaining organization IDs
    const resultIds = result.map((item) => item.organizationId);

    // Assert that the result IDs match the expected IDs
    expect(resultIds).toEqual(expectedIds);
  });
});
