export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  MISSING_REQUIRED_PARAMETER: "MISSING_REQUIRED_PARAMETER",
  CAMPAIGN_NOT_FOUND: "CAMPAIGN_NOT_FOUND",
  DOMAIN_NOT_FOUND: "DOMAIN_NOT_FOUND",
  LANGUAGE_NOT_FOUND: "LANGUAGE_NOT_FOUND",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  INVALID_JOB_GROUP: "INVALID_JOB_GROUP",
  QUIZ_SET_NOT_FOUND: "QUIZ_SET_NOT_FOUND",
  NO_DATA_FOUND: "NO_DATA_FOUND",
  UNKNOWN: "UNKNOWN",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
